### ISSUE TITLE
Adapter detects username as first name instead of the actual one

### ISSUE THREAD

**Issue by ramizh** [ioBroker/ioBroker.telegram#45]
As I was having another issue regarding the blocky script with user name field, I realised that the adapter detects me with my first name as username and not my actual username. 
Since first names are not unique this could lead to some issues down the road.
I tried to delete everything and reinstall the Adapter and bot but still it shows my first name as user and not my actual one.
Not sure if this is just me, or it is how it is.

**Comment by BuZZy1337** [comment]
The Adapter is always saving the first name of the user and not the Username that is set in the Telegram App of the user.. So that is how it is for now. I think it is working that way because it is easier to remember first names and usually you only have users on your bot which are living in your household. 

So you can easier do your scripting stuff without first have to look what the username of your wife / daughter / son is on telegram - you just need to know the first names to send messages out of the script directly to one of them. And hopefully you know the name of your family members.. :laughing:

**Comment by BuZZy1337** [comment]
For your information:
I am preparing a change on the adapter - where you can choose in the settings of the adapter if it should save the username or the first name of an user.

This is useful if somebody has multiple users with the same first name authenticated to the bot.. :+1:

**Comment by ramizh** [comment]
Of course using first names will be much easier and probably I will be using it for now, the other big issue with it is the script, as I posted on iobroker.javascript its like lottery if the thing works when using "user" in the code rather than "chatId", I dont know why but yea. 
Nevertheless I appreciate your effort to implement a second option since it solves issues with multiple names.
Thanks again !!

**Comment by BuZZy1337** [comment]
PR created:
https://github.com/ioBroker/ioBroker.telegram/pull/47

**Comment by ramizh** [comment]
Thanks a lot for the effort!!! Ill go ahead and close this one! Ill try to changes and give feedback asap!
